// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6UcsUiJ4VLmVnmJkzwZ9O1HrNly2_rE',
    appId: '1:855210758142:web:0734eb514d1eceebc13aaf',
    messagingSenderId: '855210758142',
    projectId: 'flutterecomadmin',
    authDomain: 'flutterecomadmin.firebaseapp.com',
    storageBucket: 'flutterecomadmin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALa7KX8IojAiY8IMptApILKrx3cDfZPCQ',
    appId: '1:855210758142:android:3adbe9ece597f0bfc13aaf',
    messagingSenderId: '855210758142',
    projectId: 'flutterecomadmin',
    storageBucket: 'flutterecomadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPHoQUc_yOBWtNhnW5mQKLirsvm21XXI',
    appId: '1:855210758142:ios:c26f2c2cd05e0e39c13aaf',
    messagingSenderId: '855210758142',
    projectId: 'flutterecomadmin',
    storageBucket: 'flutterecomadmin.appspot.com',
    iosClientId: '855210758142-hvrdg4j9f2cbgvquf47g4ngdmbbaetl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceBackend',
  );
}
